-- Create Database
CREATE DATABASE careplus_db;

-- Use Database
USE careplus_db;


-- ------------------------------------------------------------
-- Ticket load distribution across communication channels.
-- This extracts the number of support tickets received through
-- each channel such as Email, Chat, etc.
-- ------------------------------------------------------------
SELECT channel, COUNT(*) AS ticket_count
FROM support_tickets_processed
GROUP BY channel
ORDER BY ticket_count DESC;


-- ------------------------------------------------------------
-- Ticket status summary.
-- This extracts the total number of tickets and categorizes them
-- into resolved, open, and escalated tickets.
-- ------------------------------------------------------------
SELECT
    COUNT(*) AS total_tickets,
    SUM(CASE WHEN status = 'Resolved'  THEN 1 ELSE 0 END) AS resolved_tickets,
    SUM(CASE WHEN status = 'Open'      THEN 1 ELSE 0 END) AS open_tickets,
    SUM(CASE WHEN status = 'Escalated' THEN 1 ELSE 0 END) AS escalated_tickets
FROM support_tickets_processed;


-- ------------------------------------------------------------
-- Event volume generated by each user agent.
-- This extracts the number of log events associated with each
-- user agent to understand client activity patterns.
-- ------------------------------------------------------------
SELECT user_agent, COUNT(*) AS event_count
FROM support_logs_processed
GROUP BY user_agent
ORDER BY event_count DESC;


-- ------------------------------------------------------------
-- Daily ticket creation trend.
-- This extracts the number of support tickets created per day
-- to analyze ticket volume trends over time.
-- ------------------------------------------------------------
SELECT
    DATE(created_at) AS day,
    COUNT(*) AS tickets_created
FROM support_tickets_processed
GROUP BY DATE(created_at)
ORDER BY day;


-- ------------------------------------------------------------
-- Debug level log event count.
-- This extracts the total number of log records with DEBUG
-- level severity for monitoring diagnostic activity.
-- ------------------------------------------------------------
SELECT COUNT(*) AS debug_event_count
FROM support_logs_processed
WHERE log_level = 'DEBUG';


-- ------------------------------------------------------------
-- Average CPU usage by user agent.
-- This extracts the average CPU usage associated with each
-- user agent to analyze system resource consumption patterns.
-- ------------------------------------------------------------
SELECT user_agent, AVG(cpu) AS avg_cpu_usage
FROM support_logs_processed
GROUP BY user_agent
ORDER BY avg_cpu_usage DESC;